Category badges added
sabesansathananthan/React-Medium-Blog pull request #26
Opened 2021-11-25 16:07 UTC by Mathursan-007

issue #6 
- Category theme is not found.
- All category tags were added to the bottom of the card
![image](https://user-images.githubusercontent.com/63546506/143473460-89a3fd15-ed7f-4aee-98dc-3b3661ce217b.png)

2021-11-25 17:46 UTC, sabesansathananthan commented
Hey Can you check this  [page](https://designrevision.com/demo/shards-dashboard-lite-react/blog-posts) 
I expected like the below screenshot
![Screenshot from 2021-11-25 23-12-20](https://user-images.githubusercontent.com/36799589/143484525-bf970467-8669-4550-8136-ab3545eb2d97.png).
 you can download and play with this [repo](https://designrevision.com/downloads/shards-dashboard-lite-react/).. 
Don't worry about the styling. It is already added in the assert file.

2021-12-04 17:01 UTC, Mathursan-007 commented
> Hey Can you check this [page](https://designrevision.com/demo/shards-dashboard-lite-react/blog-posts) I expected like the below screenshot ![Screenshot from 2021-11-25 23-12-20](https://user-images.githubusercontent.com/36799589/143484525-bf970467-8669-4550-8136-ab3545eb2d97.png). you can download and play with this [repo](https://designrevision.com/downloads/shards-dashboard-lite-react/).. Don't worry about the styling. It is already added in the assert file.

Hey,
The changes have been made as you said.
- Categories are merged and sorted based on the number of counts(Ascending).
- Each post will consist of a badge with the matching tag of it in the sorted list of tags.
- Badge's color will be differentiated based on the category.

2021-12-09 19:34 UTC, sabesansathananthan requested changes
requested change

2021-12-09 19:34 UTC, sabesansathananthan commented on src/components/Slider.js
> +              item['tagNo'] = i + 1;
Tag No is wrong Correct it

2021-12-10 16:26 UTC, Mathursan-007 commented on src/components/Slider.js
> +              item['tagNo'] = i + 1;
resolved

2021-12-12 05:50 UTC, sabesansathananthan approved these changes
Thank you for your PR

2021-12-12 05:53 UTC, merged